/****************************************************************************
**
** Metadata for grdesLib generated by dumpcpp from type library
** grdes50.dll
**
****************************************************************************/

#define QAX_DUMPCPP_GRDESLIB_NOINLINES
#include "gredes.h"

using namespace grdesLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[263];
    char stringdata0[4726];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 20, 0),
QT_MOC_LITERAL(1, 21, 17, 0),
QT_MOC_LITERAL(2, 39, 18, 0),
QT_MOC_LITERAL(3, 58, 11, 0),
QT_MOC_LITERAL(4, 70, 11, 0),
QT_MOC_LITERAL(5, 82, 17, 0),
QT_MOC_LITERAL(6, 100, 0, 0),
QT_MOC_LITERAL(7, 101, 10, 0),
QT_MOC_LITERAL(8, 112, 14, 0),
QT_MOC_LITERAL(9, 127, 19, 0),
QT_MOC_LITERAL(10, 147, 6, 0),
QT_MOC_LITERAL(11, 154, 10, 0),
QT_MOC_LITERAL(12, 165, 22, 0),
QT_MOC_LITERAL(13, 188, 15, 0),
QT_MOC_LITERAL(14, 204, 19, 0),
QT_MOC_LITERAL(15, 224, 15, 0),
QT_MOC_LITERAL(16, 240, 20, 0),
QT_MOC_LITERAL(17, 261, 22, 0),
QT_MOC_LITERAL(18, 284, 17, 0),
QT_MOC_LITERAL(19, 302, 10, 0),
QT_MOC_LITERAL(20, 313, 10, 0),
QT_MOC_LITERAL(21, 324, 14, 0),
QT_MOC_LITERAL(22, 339, 7, 0),
QT_MOC_LITERAL(23, 347, 16, 0),
QT_MOC_LITERAL(24, 364, 9, 0),
QT_MOC_LITERAL(25, 374, 10, 0),
QT_MOC_LITERAL(26, 385, 19, 0),
QT_MOC_LITERAL(27, 405, 12, 0),
QT_MOC_LITERAL(28, 418, 20, 0),
QT_MOC_LITERAL(29, 439, 13, 0),
QT_MOC_LITERAL(30, 453, 18, 0),
QT_MOC_LITERAL(31, 472, 11, 0),
QT_MOC_LITERAL(32, 484, 15, 0),
QT_MOC_LITERAL(33, 500, 21, 0),
QT_MOC_LITERAL(34, 522, 8, 0),
QT_MOC_LITERAL(35, 531, 16, 0),
QT_MOC_LITERAL(36, 548, 22, 0),
QT_MOC_LITERAL(37, 571, 9, 0),
QT_MOC_LITERAL(38, 581, 19, 0),
QT_MOC_LITERAL(39, 601, 25, 0),
QT_MOC_LITERAL(40, 627, 12, 0),
QT_MOC_LITERAL(41, 640, 9, 0),
QT_MOC_LITERAL(42, 650, 4, 0),
QT_MOC_LITERAL(43, 655, 6, 0),
QT_MOC_LITERAL(44, 662, 4, 0),
QT_MOC_LITERAL(45, 667, 4, 0),
QT_MOC_LITERAL(46, 672, 15, 0),
QT_MOC_LITERAL(47, 688, 4, 0),
QT_MOC_LITERAL(48, 693, 6, 0),
QT_MOC_LITERAL(49, 700, 4, 0),
QT_MOC_LITERAL(50, 705, 4, 0),
QT_MOC_LITERAL(51, 710, 19, 0),
QT_MOC_LITERAL(52, 730, 17, 0),
QT_MOC_LITERAL(53, 748, 19, 0),
QT_MOC_LITERAL(54, 768, 8, 0),
QT_MOC_LITERAL(55, 777, 16, 0),
QT_MOC_LITERAL(56, 794, 18, 0),
QT_MOC_LITERAL(57, 813, 14, 0),
QT_MOC_LITERAL(58, 828, 17, 0),
QT_MOC_LITERAL(59, 846, 19, 0),
QT_MOC_LITERAL(60, 866, 17, 0),
QT_MOC_LITERAL(61, 884, 18, 0),
QT_MOC_LITERAL(62, 903, 26, 0),
QT_MOC_LITERAL(63, 930, 22, 0),
QT_MOC_LITERAL(64, 953, 13, 0),
QT_MOC_LITERAL(65, 967, 5, 0),
QT_MOC_LITERAL(66, 973, 18, 0),
QT_MOC_LITERAL(67, 992, 24, 0),
QT_MOC_LITERAL(68, 1017, 13, 0),
QT_MOC_LITERAL(69, 1031, 24, 0),
QT_MOC_LITERAL(70, 1056, 14, 0),
QT_MOC_LITERAL(71, 1071, 19, 0),
QT_MOC_LITERAL(72, 1091, 6, 0),
QT_MOC_LITERAL(73, 1098, 17, 0),
QT_MOC_LITERAL(74, 1116, 21, 0),
QT_MOC_LITERAL(75, 1138, 16, 0),
QT_MOC_LITERAL(76, 1155, 15, 0),
QT_MOC_LITERAL(77, 1171, 22, 0),
QT_MOC_LITERAL(78, 1194, 27, 0),
QT_MOC_LITERAL(79, 1222, 22, 0),
QT_MOC_LITERAL(80, 1245, 27, 0),
QT_MOC_LITERAL(81, 1273, 4, 0),
QT_MOC_LITERAL(82, 1278, 20, 0),
QT_MOC_LITERAL(83, 1299, 11, 0),
QT_MOC_LITERAL(84, 1311, 6, 0),
QT_MOC_LITERAL(85, 1318, 11, 0),
QT_MOC_LITERAL(86, 1330, 8, 0),
QT_MOC_LITERAL(87, 1339, 13, 0),
QT_MOC_LITERAL(88, 1353, 16, 0),
QT_MOC_LITERAL(89, 1370, 13, 0),
QT_MOC_LITERAL(90, 1384, 18, 0),
QT_MOC_LITERAL(91, 1403, 15, 0),
QT_MOC_LITERAL(92, 1419, 18, 0),
QT_MOC_LITERAL(93, 1438, 15, 0),
QT_MOC_LITERAL(94, 1454, 8, 0),
QT_MOC_LITERAL(95, 1463, 5, 0),
QT_MOC_LITERAL(96, 1469, 18, 0),
QT_MOC_LITERAL(97, 1488, 18, 0),
QT_MOC_LITERAL(98, 1507, 9, 0),
QT_MOC_LITERAL(99, 1517, 17, 0),
QT_MOC_LITERAL(100, 1535, 8, 0),
QT_MOC_LITERAL(101, 1544, 18, 0),
QT_MOC_LITERAL(102, 1563, 9, 0),
QT_MOC_LITERAL(103, 1573, 18, 0),
QT_MOC_LITERAL(104, 1592, 9, 0),
QT_MOC_LITERAL(105, 1602, 13, 0),
QT_MOC_LITERAL(106, 1616, 14, 0),
QT_MOC_LITERAL(107, 1631, 6, 0),
QT_MOC_LITERAL(108, 1638, 10, 0),
QT_MOC_LITERAL(109, 1649, 12, 0),
QT_MOC_LITERAL(110, 1662, 17, 0),
QT_MOC_LITERAL(111, 1680, 9, 0),
QT_MOC_LITERAL(112, 1690, 10, 0),
QT_MOC_LITERAL(113, 1701, 6, 0),
QT_MOC_LITERAL(114, 1708, 15, 0),
QT_MOC_LITERAL(115, 1724, 16, 0),
QT_MOC_LITERAL(116, 1741, 14, 0),
QT_MOC_LITERAL(117, 1756, 19, 0),
QT_MOC_LITERAL(118, 1776, 16, 0),
QT_MOC_LITERAL(119, 1793, 11, 0),
QT_MOC_LITERAL(120, 1805, 12, 0),
QT_MOC_LITERAL(121, 1818, 15, 0),
QT_MOC_LITERAL(122, 1834, 17, 0),
QT_MOC_LITERAL(123, 1852, 9, 0),
QT_MOC_LITERAL(124, 1862, 6, 0),
QT_MOC_LITERAL(125, 1869, 15, 0),
QT_MOC_LITERAL(126, 1885, 12, 0),
QT_MOC_LITERAL(127, 1898, 14, 0),
QT_MOC_LITERAL(128, 1913, 7, 0),
QT_MOC_LITERAL(129, 1921, 18, 0),
QT_MOC_LITERAL(130, 1940, 12, 0),
QT_MOC_LITERAL(131, 1953, 12, 0),
QT_MOC_LITERAL(132, 1966, 11, 0),
QT_MOC_LITERAL(133, 1978, 13, 0),
QT_MOC_LITERAL(134, 1992, 12, 0),
QT_MOC_LITERAL(135, 2005, 14, 0),
QT_MOC_LITERAL(136, 2020, 17, 0),
QT_MOC_LITERAL(137, 2038, 19, 0),
QT_MOC_LITERAL(138, 2058, 17, 0),
QT_MOC_LITERAL(139, 2076, 16, 0),
QT_MOC_LITERAL(140, 2093, 17, 0),
QT_MOC_LITERAL(141, 2111, 19, 0),
QT_MOC_LITERAL(142, 2131, 20, 0),
QT_MOC_LITERAL(143, 2152, 22, 0),
QT_MOC_LITERAL(144, 2175, 16, 0),
QT_MOC_LITERAL(145, 2192, 29, 0),
QT_MOC_LITERAL(146, 2222, 25, 0),
QT_MOC_LITERAL(147, 2248, 26, 0),
QT_MOC_LITERAL(148, 2275, 25, 0),
QT_MOC_LITERAL(149, 2301, 27, 0),
QT_MOC_LITERAL(150, 2329, 20, 0),
QT_MOC_LITERAL(151, 2350, 23, 0),
QT_MOC_LITERAL(152, 2374, 21, 0),
QT_MOC_LITERAL(153, 2396, 22, 0),
QT_MOC_LITERAL(154, 2419, 22, 0),
QT_MOC_LITERAL(155, 2442, 20, 0),
QT_MOC_LITERAL(156, 2463, 20, 0),
QT_MOC_LITERAL(157, 2484, 20, 0),
QT_MOC_LITERAL(158, 2505, 15, 0),
QT_MOC_LITERAL(159, 2521, 15, 0),
QT_MOC_LITERAL(160, 2537, 16, 0),
QT_MOC_LITERAL(161, 2554, 19, 0),
QT_MOC_LITERAL(162, 2574, 19, 0),
QT_MOC_LITERAL(163, 2594, 20, 0),
QT_MOC_LITERAL(164, 2615, 21, 0),
QT_MOC_LITERAL(165, 2637, 18, 0),
QT_MOC_LITERAL(166, 2656, 21, 0),
QT_MOC_LITERAL(167, 2678, 21, 0),
QT_MOC_LITERAL(168, 2700, 21, 0),
QT_MOC_LITERAL(169, 2722, 23, 0),
QT_MOC_LITERAL(170, 2746, 24, 0),
QT_MOC_LITERAL(171, 2771, 22, 0),
QT_MOC_LITERAL(172, 2794, 20, 0),
QT_MOC_LITERAL(173, 2815, 30, 0),
QT_MOC_LITERAL(174, 2846, 31, 0),
QT_MOC_LITERAL(175, 2878, 31, 0),
QT_MOC_LITERAL(176, 2910, 32, 0),
QT_MOC_LITERAL(177, 2943, 33, 0),
QT_MOC_LITERAL(178, 2977, 33, 0),
QT_MOC_LITERAL(179, 3011, 31, 0),
QT_MOC_LITERAL(180, 3043, 29, 0),
QT_MOC_LITERAL(181, 3073, 27, 0),
QT_MOC_LITERAL(182, 3101, 25, 0),
QT_MOC_LITERAL(183, 3127, 27, 0),
QT_MOC_LITERAL(184, 3155, 18, 0),
QT_MOC_LITERAL(185, 3174, 20, 0),
QT_MOC_LITERAL(186, 3195, 23, 0),
QT_MOC_LITERAL(187, 3219, 26, 0),
QT_MOC_LITERAL(188, 3246, 28, 0),
QT_MOC_LITERAL(189, 3275, 27, 0),
QT_MOC_LITERAL(190, 3303, 29, 0),
QT_MOC_LITERAL(191, 3333, 31, 0),
QT_MOC_LITERAL(192, 3365, 30, 0),
QT_MOC_LITERAL(193, 3396, 29, 0),
QT_MOC_LITERAL(194, 3426, 31, 0),
QT_MOC_LITERAL(195, 3458, 30, 0),
QT_MOC_LITERAL(196, 3489, 32, 0),
QT_MOC_LITERAL(197, 3522, 32, 0),
QT_MOC_LITERAL(198, 3555, 32, 0),
QT_MOC_LITERAL(199, 3588, 32, 0),
QT_MOC_LITERAL(200, 3621, 32, 0),
QT_MOC_LITERAL(201, 3654, 31, 0),
QT_MOC_LITERAL(202, 3686, 13, 0),
QT_MOC_LITERAL(203, 3700, 16, 0),
QT_MOC_LITERAL(204, 3717, 17, 0),
QT_MOC_LITERAL(205, 3735, 29, 0),
QT_MOC_LITERAL(206, 3765, 16, 0),
QT_MOC_LITERAL(207, 3782, 15, 0),
QT_MOC_LITERAL(208, 3798, 19, 0),
QT_MOC_LITERAL(209, 3818, 18, 0),
QT_MOC_LITERAL(210, 3837, 20, 0),
QT_MOC_LITERAL(211, 3858, 19, 0),
QT_MOC_LITERAL(212, 3878, 19, 0),
QT_MOC_LITERAL(213, 3898, 19, 0),
QT_MOC_LITERAL(214, 3918, 25, 0),
QT_MOC_LITERAL(215, 3944, 29, 0),
QT_MOC_LITERAL(216, 3974, 23, 0),
QT_MOC_LITERAL(217, 3998, 18, 0),
QT_MOC_LITERAL(218, 4017, 16, 0),
QT_MOC_LITERAL(219, 4034, 11, 0),
QT_MOC_LITERAL(220, 4046, 13, 0),
QT_MOC_LITERAL(221, 4060, 12, 0),
QT_MOC_LITERAL(222, 4073, 14, 0),
QT_MOC_LITERAL(223, 4088, 12, 0),
QT_MOC_LITERAL(224, 4101, 14, 0),
QT_MOC_LITERAL(225, 4116, 14, 0),
QT_MOC_LITERAL(226, 4131, 21, 0),
QT_MOC_LITERAL(227, 4153, 13, 0),
QT_MOC_LITERAL(228, 4167, 20, 0),
QT_MOC_LITERAL(229, 4188, 18, 0),
QT_MOC_LITERAL(230, 4207, 25, 0),
QT_MOC_LITERAL(231, 4233, 17, 0),
QT_MOC_LITERAL(232, 4251, 18, 0),
QT_MOC_LITERAL(233, 4270, 10, 0),
QT_MOC_LITERAL(234, 4281, 10, 0),
QT_MOC_LITERAL(235, 4292, 14, 0),
QT_MOC_LITERAL(236, 4307, 8, 0),
QT_MOC_LITERAL(237, 4316, 10, 0),
QT_MOC_LITERAL(238, 4327, 9, 0),
QT_MOC_LITERAL(239, 4337, 8, 0),
QT_MOC_LITERAL(240, 4346, 11, 0),
QT_MOC_LITERAL(241, 4358, 15, 0),
QT_MOC_LITERAL(242, 4374, 15, 0),
QT_MOC_LITERAL(243, 4390, 17, 0),
QT_MOC_LITERAL(244, 4408, 17, 0),
QT_MOC_LITERAL(245, 4426, 18, 0),
QT_MOC_LITERAL(246, 4445, 17, 0),
QT_MOC_LITERAL(247, 4463, 15, 0),
QT_MOC_LITERAL(248, 4479, 11, 0),
QT_MOC_LITERAL(249, 4491, 22, 0),
QT_MOC_LITERAL(250, 4514, 20, 0),
QT_MOC_LITERAL(251, 4535, 18, 0),
QT_MOC_LITERAL(252, 4554, 16, 0),
QT_MOC_LITERAL(253, 4571, 10, 0),
QT_MOC_LITERAL(254, 4582, 16, 0),
QT_MOC_LITERAL(255, 4599, 16, 0),
QT_MOC_LITERAL(256, 4616, 14, 0),
QT_MOC_LITERAL(257, 4631, 10, 0),
QT_MOC_LITERAL(258, 4642, 14, 0),
QT_MOC_LITERAL(259, 4657, 13, 0),
QT_MOC_LITERAL(260, 4671, 21, 0),
QT_MOC_LITERAL(261, 4693, 7, 0),
QT_MOC_LITERAL(262, 4701, 23, 0)
    },
    "grdesLib::GRDesigner\0Event Interface 1\0_IGRDesignerEvents\0Interface 0\0"
    "IGRDesigner\0AsNativeUIChanged\0\0AsNativeUI\0BeforeDoAction\0tagGRDesignerAction\0"
    "Action\0DataChange\0EnableQuickEditChanged\0EnableQuickEdit\0ExplorerContextMenu\0"
    "InspectorChange\0InspectorContextMenu\0LayoutPanelContextMenu\0OnlyLayoutChanged\0"
    "OnlyLayout\0OpenReport\0OptionsChanged\0Options\0PublishedChanged\0Published\0"
    "SaveReport\0ShowExplorerChanged\0ShowExplorer\0ShowInspectorChanged\0ShowInspector\0"
    "ShowToolbarChanged\0ShowToolbar\0ViewModeChanged\0tagGRDesignerViewMode\0ViewMode\0"
    "ViewStyleChanged\0tagGRDesignerViewStyle\0ViewStyle\0WindowLayoutChanged\0"
    "tagGRDesignerWindowLayout\0WindowLayout\0exception\0code\0source\0disc\0help\0"
    "propertyChanged\0name\0signal\0argc\0argv\0CancelInsertControl\0DisableAllOptions\0"
    "DisableAllPublished\0DoAction\0EnableAllOptions\0EnableAllPublished\0GetObjectCount\0"
    "GetObjectFontBold\0GetObjectFontItalic\0GetObjectFontName\0GetObjectFontPoint\0"
    "GetObjectFontStrikethrough\0GetObjectFontUnderline\0GetObjectName\0Index\0"
    "GetObjectTextAlign\0GetObjectTextOrientation\0GetObjectType\0tagGRSelectionObjectType\0"
    "GetOptionValue\0tagGRDesignerOption\0Option\0GetPublishedValue\0tagGRPropertyCategory\0"
    "PropertyCategory\0IsActionEnabled\0IsInsertControlEnabled\0IsSetObjectBackColorEnabled\0"
    "IsSetObjectFontEnabled\0IsSetObjectForeColorEnabled\0Post\0PrepareInsertControl\0"
    "ControlType\0Reload\0SetAsFormUI\0AsFormUI\0SetAsNativeUI\0SetDefaultAction\0"
    "DefaultAction\0SetDesignEdgeColor\0DesignEdgeColor\0SetDesignGridColor\0"
    "DesignGridColor\0SetDirty\0Dirty\0SetEnableQuickEdit\0SetObjectBackColor\0BackColor\0"
    "SetObjectFontName\0FontName\0SetObjectFontPoint\0FontPoint\0SetObjectForeColor\0"
    "FontColor\0SetOnlyLayout\0SetOptionValue\0newVal\0SetOptions\0SetPublished\0"
    "SetPublishedValue\0SetReport\0IDispatch*\0Report\0SetShowExplorer\0SetShowInspector\0"
    "SetShowToolbar\0SetViewFloatSection\0ViewFloatSection\0SetViewMode\0SetViewStyle\0"
    "SetWindowLayout\0ShowClassProperty\0ClassName\0IsShow\0ShowOneProperty\0PropertyName\0"
    "UpdateLanguage\0IsBlank\0IsInsertingControl\0grdaEditUndo\0grdaEditRedo\0grdaEditCut\0"
    "grdaEditPaste\0grdaEditCopy\0grdaEditDelete\0grdaEditSelectAll\0grdaAutoSizeControl\0"
    "grdaAutoGenColumn\0grdaAutoGenField\0grdaSectionMoveUp\0grdaSectionMoveDown\0"
    "grdaAutoGenParameter\0grdaReportPaperSetting\0grdaSetupDBQuery\0"
    "grdaReportParameterCollection\0grdaReportGroupCollection\0grdaReportColumnCollection\0"
    "grdaReportFieldCollection\0grdaReportColumnTitleLayout\0grdaBrowseScriptCode\0"
    "grdaExitSubReportDesign\0grdaSetupParamDBQuery\0grdaInsertReportHeader\0"
    "grdaInsertReportFooter\0grdaInsertPageHeader\0grdaInsertPageFooter\0"
    "grdaInsertDetailGrid\0grdaInsertGroup\0grdaInsertField\0grdaInsertColumn\0"
    "grdaInsertParameter\0grdaFormatAlignLeft\0grdaFormatAlignRight\0grdaFormatAlignCenter\0"
    "grdaFormatAlignTop\0grdaFormatAlignMiddle\0grdaFormatAlignBottom\0grdaFormatAlignToGrid\0"
    "grdaFormatSizeSameWidth\0grdaFormatSizeSameHeight\0grdaFormatSizeSameBoth\0"
    "grdaFormatSizeToGrid\0grdaFormatSpaceEquallyVertical\0grdaFormatSpaceIncreaseVertical\0"
    "grdaFormatSpaceDecreaseVertical\0grdaFormatSpaceEquallyHorizontal\0"
    "grdaFormatSpaceIncreaseHorizontal\0grdaFormatSpaceDecreaseHorizontal\0"
    "grdaFormatSpaceRemoveHorizontal\0grdaFormatSpaceRemoveVertical\0"
    "grdaFormatOrderBringToFront\0grdaFormatOrderSendToBack\0grdaFormatFontStrikethrough\0"
    "grdaFormatFontBold\0grdaFormatFontItalic\0grdaFormatFontUnderline\0"
    "grdaFormatTextAlignTopLeft\0grdaFormatTextAlignTopCenter\0grdaFormatTextAlignTopRight\0"
    "grdaFormatTextAlignMiddleLeft\0grdaFormatTextAlignMiddleCenter\0"
    "grdaFormatTextAlignMiddleRight\0grdaFormatTextAlignBottomLeft\0"
    "grdaFormatTextAlignBottomCenter\0grdaFormatTextAlignBottomRight\0"
    "grdaFormatTextOrientationDefault\0grdaFormatTextOrientationU2DL2R0\0"
    "grdaFormatTextOrientationD2UL2R1\0grdaFormatTextOrientationU2DR2L0\0"
    "grdaFormatTextOrientationU2DR2L1\0grdaFormatTextOrientationInvert\0grdoShowRuler\0"
    "grdoCanPopupMenu\0grdoShowInspector\0grdoShowInspectorObjectPicker\0grdoShowExplorer\0"
    "grdoShowToolbar\0grdoShowSectionLine\0grdoShowMarginLine\0grdoCanResizeSection\0"
    "grdoCanChangeMargin\0grdoCanDeleteObject\0grdoEnableQuickEdit\0grdoShowDetailGridToolbar\0"
    "grdoShowDetailGridColumnRuler\0grdoCanModifyDBSettings\0grvmInNormalDesign\0"
    "grvmInPageDesign\0grvmInPrint\0grvmInDisplay\0grvmInScript\0grvsOnlyNormal\0"
    "grvsOnlyPage\0grvsNormalPage\0grvsNomalPrint\0grvsNomalPrintDisplay\0grvsPagePrint\0"
    "grvsPagePrintDisplay\0grvsNomalPagePrint\0grvsNomalPagePrintDisplay\0grdwlLayoutAtLeft\0"
    "grdwlLayoutAtRight\0grpcDesign\0grpcLayout\0grpcAppearance\0grpcData\0grpcAction\0"
    "grpcEvent\0grpcMisc\0grdssReport\0grdssPageHeader\0grdssPageFooter\0grdssReportHeader\0"
    "grdssReportFooter\0grdssControlSingle\0grdssControlMulti\0grdssDetailGrid\0"
    "grdssColumn\0grdssColumnContentCell\0grdssColumnTitleCell\0grdssColumnContent\0"
    "grdssColumnTitle\0grdssGroup\0grdssGroupHeader\0grdssGroupFooter\0grdssRecordset\0"
    "grdssField\0grdssParameter\0grdssCrossTab\0grdesLib::IGRDesigner\0control\0"
    "grdesLib::DesignerProps\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_grdesLib__GRDesigner[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    76, 18, // methods
    20, 588, // properties
    7, 648, // enums/sets
    0, 0, // constructors
    0, // flags
    22, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 1, 398, 6, 5,
    8, 1, 401, 6, 5,
    11, 0, 404, 6, 5,
    12, 1, 405, 6, 5,
    14, 0, 408, 6, 5,
    15, 0, 409, 6, 5,
    16, 0, 410, 6, 5,
    17, 0, 411, 6, 5,
    18, 1, 412, 6, 5,
    20, 0, 415, 6, 5,
    21, 1, 416, 6, 5,
    23, 1, 419, 6, 5,
    25, 0, 422, 6, 5,
    26, 1, 423, 6, 5,
    28, 1, 426, 6, 5,
    30, 1, 429, 6, 5,
    32, 1, 432, 6, 5,
    35, 1, 435, 6, 5,
    38, 1, 438, 6, 5,
    41, 4, 441, 6, 5,
    46, 1, 450, 6, 5,
    48, 3, 453, 6, 5,

// slot: name, argc, parameters, tag, flags
    51, 0, 460, 6, 9,
    52, 0, 461, 6, 9,
    53, 0, 462, 6, 9,
    54, 1, 463, 6, 9,
    55, 0, 466, 6, 9,
    56, 0, 467, 6, 9,
    57, 0, 468, 6, 9,
    58, 0, 469, 6, 9,
    59, 0, 470, 6, 9,
    60, 0, 471, 6, 9,
    61, 0, 472, 6, 9,
    62, 0, 473, 6, 9,
    63, 0, 474, 6, 9,
    64, 1, 475, 6, 9,
    66, 0, 478, 6, 9,
    67, 0, 479, 6, 9,
    68, 0, 480, 6, 9,
    70, 1, 481, 6, 9,
    73, 1, 484, 6, 9,
    76, 1, 487, 6, 9,
    77, 0, 490, 6, 9,
    78, 0, 491, 6, 9,
    79, 0, 492, 6, 9,
    80, 0, 493, 6, 9,
    81, 0, 494, 6, 9,
    82, 1, 495, 6, 9,
    84, 0, 498, 6, 9,
    85, 1, 499, 6, 9,
    87, 1, 502, 6, 9,
    88, 1, 505, 6, 9,
    90, 1, 508, 6, 9,
    92, 1, 511, 6, 9,
    94, 1, 514, 6, 9,
    96, 1, 517, 6, 9,
    97, 1, 520, 6, 9,
    99, 1, 523, 6, 9,
    101, 1, 526, 6, 9,
    103, 1, 529, 6, 9,
    105, 1, 532, 6, 9,
    106, 2, 535, 6, 9,
    108, 1, 540, 6, 9,
    109, 1, 543, 6, 9,
    110, 2, 546, 6, 9,
    111, 1, 551, 6, 9,
    114, 1, 554, 6, 9,
    115, 1, 557, 6, 9,
    116, 1, 560, 6, 9,
    117, 1, 563, 6, 9,
    119, 1, 566, 6, 9,
    120, 1, 569, 6, 9,
    121, 1, 572, 6, 9,
    122, 2, 575, 6, 9,
    125, 3, 580, 6, 9,
    127, 0, 587, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, 0x80000000 | 9, 10,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 13,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 19,
    QMetaType::Void,
    QMetaType::Void, QMetaType::UInt, 22,
    QMetaType::Void, QMetaType::UInt, 24,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 27,
    QMetaType::Void, QMetaType::Bool, 29,
    QMetaType::Void, QMetaType::Bool, 31,
    QMetaType::Void, 0x80000000 | 33, 34,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, 0x80000000 | 39, 40,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 42, 43, 44, 45,
    QMetaType::Void, QMetaType::QString, 47,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 47, 49, 50,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 9, 10,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::QString,
    QMetaType::Double,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::QString, QMetaType::Int, 65,
    QMetaType::Int,
    QMetaType::Int,
    0x80000000 | 69,
    QMetaType::Bool, 0x80000000 | 71, 72,
    QMetaType::Bool, 0x80000000 | 74, 75,
    QMetaType::Bool, 0x80000000 | 9, 10,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 83,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 86,
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, QMetaType::Bool, 89,
    QMetaType::Void, QMetaType::QColor, 91,
    QMetaType::Void, QMetaType::QColor, 93,
    QMetaType::Void, QMetaType::Bool, 95,
    QMetaType::Void, QMetaType::Bool, 13,
    QMetaType::Void, QMetaType::QColor, 98,
    QMetaType::Void, QMetaType::QString, 100,
    QMetaType::Void, QMetaType::Double, 102,
    QMetaType::Void, QMetaType::QColor, 104,
    QMetaType::Void, QMetaType::Bool, 19,
    QMetaType::Void, 0x80000000 | 71, QMetaType::Bool, 72, 107,
    QMetaType::Void, QMetaType::UInt, 22,
    QMetaType::Void, QMetaType::UInt, 24,
    QMetaType::Void, 0x80000000 | 74, QMetaType::Bool, 75, 107,
    QMetaType::Void, 0x80000000 | 112, 113,
    QMetaType::Void, QMetaType::Bool, 27,
    QMetaType::Void, QMetaType::Bool, 29,
    QMetaType::Void, QMetaType::Bool, 31,
    QMetaType::Void, QMetaType::Bool, 118,
    QMetaType::Void, 0x80000000 | 33, 34,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, 0x80000000 | 39, 40,
    QMetaType::Void, QMetaType::QString, QMetaType::Bool, 123, 124,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Bool, 123, 126, 124,
    QMetaType::Void,

 // properties: name, type, flags
    86, QMetaType::Bool, 0x01015003, 		 // bool AsFormUI
    7, QMetaType::Bool, 0x01015003, 		 // bool AsNativeUI
    89, QMetaType::Bool, 0x01015003, 		 // bool DefaultAction
    91, QMetaType::QColor, 0x43015003, 		 // QColor DesignEdgeColor
    93, QMetaType::QColor, 0x43015003, 		 // QColor DesignGridColor
    95, QMetaType::Bool, 0x01015003, 		 // bool Dirty
    13, QMetaType::Bool, 0x01015003, 		 // bool EnableQuickEdit
    128, QMetaType::Bool, 0x01005001, 		 // bool IsBlank
    129, QMetaType::Bool, 0x01005001, 		 // bool IsInsertingControl
    19, QMetaType::Bool, 0x01015003, 		 // bool OnlyLayout
    22, QMetaType::UInt, 0x03015003, 		 // uint Options
    24, QMetaType::UInt, 0x03015003, 		 // uint Published
    113, 0x80000000 | 112, 0x00015003, 		 // IDispatch* Report
    27, QMetaType::Bool, 0x01015003, 		 // bool ShowExplorer
    29, QMetaType::Bool, 0x01015003, 		 // bool ShowInspector
    31, QMetaType::Bool, 0x01015003, 		 // bool ShowToolbar
    118, QMetaType::Bool, 0x01015003, 		 // bool ViewFloatSection
    34, 0x80000000 | 33, 0x0201500b, 		 // tagGRDesignerViewMode ViewMode
    37, 0x80000000 | 36, 0x0201500b, 		 // tagGRDesignerViewStyle ViewStyle
    40, 0x80000000 | 39, 0x0201500b, 		 // tagGRDesignerWindowLayout WindowLayout

 // enums: name, flags, count, data
    9, 0x0, 72, 676, 
    71, 0x0, 15, 820, 
    33, 0x0, 5, 850, 
    36, 0x0, 9, 860, 
    39, 0x0, 2, 878, 
    74, 0x0, 7, 882, 
    69, 0x0, 20, 896, 

 // enum data: key, value
    130, uint(grdesLib::grdaEditUndo),
    131, uint(grdesLib::grdaEditRedo),
    132, uint(grdesLib::grdaEditCut),
    133, uint(grdesLib::grdaEditPaste),
    134, uint(grdesLib::grdaEditCopy),
    135, uint(grdesLib::grdaEditDelete),
    136, uint(grdesLib::grdaEditSelectAll),
    137, uint(grdesLib::grdaAutoSizeControl),
    138, uint(grdesLib::grdaAutoGenColumn),
    139, uint(grdesLib::grdaAutoGenField),
    140, uint(grdesLib::grdaSectionMoveUp),
    141, uint(grdesLib::grdaSectionMoveDown),
    142, uint(grdesLib::grdaAutoGenParameter),
    143, uint(grdesLib::grdaReportPaperSetting),
    144, uint(grdesLib::grdaSetupDBQuery),
    145, uint(grdesLib::grdaReportParameterCollection),
    146, uint(grdesLib::grdaReportGroupCollection),
    147, uint(grdesLib::grdaReportColumnCollection),
    148, uint(grdesLib::grdaReportFieldCollection),
    149, uint(grdesLib::grdaReportColumnTitleLayout),
    150, uint(grdesLib::grdaBrowseScriptCode),
    151, uint(grdesLib::grdaExitSubReportDesign),
    152, uint(grdesLib::grdaSetupParamDBQuery),
    153, uint(grdesLib::grdaInsertReportHeader),
    154, uint(grdesLib::grdaInsertReportFooter),
    155, uint(grdesLib::grdaInsertPageHeader),
    156, uint(grdesLib::grdaInsertPageFooter),
    157, uint(grdesLib::grdaInsertDetailGrid),
    158, uint(grdesLib::grdaInsertGroup),
    159, uint(grdesLib::grdaInsertField),
    160, uint(grdesLib::grdaInsertColumn),
    161, uint(grdesLib::grdaInsertParameter),
    162, uint(grdesLib::grdaFormatAlignLeft),
    163, uint(grdesLib::grdaFormatAlignRight),
    164, uint(grdesLib::grdaFormatAlignCenter),
    165, uint(grdesLib::grdaFormatAlignTop),
    166, uint(grdesLib::grdaFormatAlignMiddle),
    167, uint(grdesLib::grdaFormatAlignBottom),
    168, uint(grdesLib::grdaFormatAlignToGrid),
    169, uint(grdesLib::grdaFormatSizeSameWidth),
    170, uint(grdesLib::grdaFormatSizeSameHeight),
    171, uint(grdesLib::grdaFormatSizeSameBoth),
    172, uint(grdesLib::grdaFormatSizeToGrid),
    173, uint(grdesLib::grdaFormatSpaceEquallyVertical),
    174, uint(grdesLib::grdaFormatSpaceIncreaseVertical),
    175, uint(grdesLib::grdaFormatSpaceDecreaseVertical),
    176, uint(grdesLib::grdaFormatSpaceEquallyHorizontal),
    177, uint(grdesLib::grdaFormatSpaceIncreaseHorizontal),
    178, uint(grdesLib::grdaFormatSpaceDecreaseHorizontal),
    179, uint(grdesLib::grdaFormatSpaceRemoveHorizontal),
    180, uint(grdesLib::grdaFormatSpaceRemoveVertical),
    181, uint(grdesLib::grdaFormatOrderBringToFront),
    182, uint(grdesLib::grdaFormatOrderSendToBack),
    183, uint(grdesLib::grdaFormatFontStrikethrough),
    184, uint(grdesLib::grdaFormatFontBold),
    185, uint(grdesLib::grdaFormatFontItalic),
    186, uint(grdesLib::grdaFormatFontUnderline),
    187, uint(grdesLib::grdaFormatTextAlignTopLeft),
    188, uint(grdesLib::grdaFormatTextAlignTopCenter),
    189, uint(grdesLib::grdaFormatTextAlignTopRight),
    190, uint(grdesLib::grdaFormatTextAlignMiddleLeft),
    191, uint(grdesLib::grdaFormatTextAlignMiddleCenter),
    192, uint(grdesLib::grdaFormatTextAlignMiddleRight),
    193, uint(grdesLib::grdaFormatTextAlignBottomLeft),
    194, uint(grdesLib::grdaFormatTextAlignBottomCenter),
    195, uint(grdesLib::grdaFormatTextAlignBottomRight),
    196, uint(grdesLib::grdaFormatTextOrientationDefault),
    197, uint(grdesLib::grdaFormatTextOrientationU2DL2R0),
    198, uint(grdesLib::grdaFormatTextOrientationD2UL2R1),
    199, uint(grdesLib::grdaFormatTextOrientationU2DR2L0),
    200, uint(grdesLib::grdaFormatTextOrientationU2DR2L1),
    201, uint(grdesLib::grdaFormatTextOrientationInvert),
    202, uint(grdesLib::grdoShowRuler),
    203, uint(grdesLib::grdoCanPopupMenu),
    204, uint(grdesLib::grdoShowInspector),
    205, uint(grdesLib::grdoShowInspectorObjectPicker),
    206, uint(grdesLib::grdoShowExplorer),
    207, uint(grdesLib::grdoShowToolbar),
    208, uint(grdesLib::grdoShowSectionLine),
    209, uint(grdesLib::grdoShowMarginLine),
    210, uint(grdesLib::grdoCanResizeSection),
    211, uint(grdesLib::grdoCanChangeMargin),
    212, uint(grdesLib::grdoCanDeleteObject),
    213, uint(grdesLib::grdoEnableQuickEdit),
    214, uint(grdesLib::grdoShowDetailGridToolbar),
    215, uint(grdesLib::grdoShowDetailGridColumnRuler),
    216, uint(grdesLib::grdoCanModifyDBSettings),
    217, uint(grdesLib::grvmInNormalDesign),
    218, uint(grdesLib::grvmInPageDesign),
    219, uint(grdesLib::grvmInPrint),
    220, uint(grdesLib::grvmInDisplay),
    221, uint(grdesLib::grvmInScript),
    222, uint(grdesLib::grvsOnlyNormal),
    223, uint(grdesLib::grvsOnlyPage),
    224, uint(grdesLib::grvsNormalPage),
    225, uint(grdesLib::grvsNomalPrint),
    226, uint(grdesLib::grvsNomalPrintDisplay),
    227, uint(grdesLib::grvsPagePrint),
    228, uint(grdesLib::grvsPagePrintDisplay),
    229, uint(grdesLib::grvsNomalPagePrint),
    230, uint(grdesLib::grvsNomalPagePrintDisplay),
    231, uint(grdesLib::grdwlLayoutAtLeft),
    232, uint(grdesLib::grdwlLayoutAtRight),
    233, uint(grdesLib::grpcDesign),
    234, uint(grdesLib::grpcLayout),
    235, uint(grdesLib::grpcAppearance),
    236, uint(grdesLib::grpcData),
    237, uint(grdesLib::grpcAction),
    238, uint(grdesLib::grpcEvent),
    239, uint(grdesLib::grpcMisc),
    240, uint(grdesLib::grdssReport),
    241, uint(grdesLib::grdssPageHeader),
    242, uint(grdesLib::grdssPageFooter),
    243, uint(grdesLib::grdssReportHeader),
    244, uint(grdesLib::grdssReportFooter),
    245, uint(grdesLib::grdssControlSingle),
    246, uint(grdesLib::grdssControlMulti),
    247, uint(grdesLib::grdssDetailGrid),
    248, uint(grdesLib::grdssColumn),
    249, uint(grdesLib::grdssColumnContentCell),
    250, uint(grdesLib::grdssColumnTitleCell),
    251, uint(grdesLib::grdssColumnContent),
    252, uint(grdesLib::grdssColumnTitle),
    253, uint(grdesLib::grdssGroup),
    254, uint(grdesLib::grdssGroupHeader),
    255, uint(grdesLib::grdssGroupFooter),
    256, uint(grdesLib::grdssRecordset),
    257, uint(grdesLib::grdssField),
    258, uint(grdesLib::grdssParameter),
    259, uint(grdesLib::grdssCrossTab),
    0 // eod
};

const QMetaObject GRDesigner::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_grdesLib__GRDesigner, 0, 0, 0 }
};

void *GRDesigner::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "grdesLib::GRDesigner"))
        return static_cast<void*>(const_cast<GRDesigner*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_grdesLib__IGRDesigner[] = {

 // content:
    7, // revision
    260,  // classname
    0, 0, // classinfo
    68, 14, // methods
    21, 534, // properties
    7, 597, // enums/sets
    0, 0, // constructors
    0, // flags
    14, // signal count

// signal: name, argc, parameters, tag, flags
    5, 1, 354, 6, 5,
    12, 1, 357, 6, 5,
    18, 1, 360, 6, 5,
    21, 1, 363, 6, 5,
    23, 1, 366, 6, 5,
    26, 1, 369, 6, 5,
    28, 1, 372, 6, 5,
    30, 1, 375, 6, 5,
    32, 1, 378, 6, 5,
    35, 1, 381, 6, 5,
    38, 1, 384, 6, 5,
    41, 4, 387, 6, 5,
    46, 1, 396, 6, 5,
    48, 3, 399, 6, 5,

// slot: name, argc, parameters, tag, flags
    51, 0, 406, 6, 9,
    52, 0, 407, 6, 9,
    53, 0, 408, 6, 9,
    54, 1, 409, 6, 9,
    55, 0, 412, 6, 9,
    56, 0, 413, 6, 9,
    57, 0, 414, 6, 9,
    58, 0, 415, 6, 9,
    59, 0, 416, 6, 9,
    60, 0, 417, 6, 9,
    61, 0, 418, 6, 9,
    62, 0, 419, 6, 9,
    63, 0, 420, 6, 9,
    64, 1, 421, 6, 9,
    66, 0, 424, 6, 9,
    67, 0, 425, 6, 9,
    68, 0, 426, 6, 9,
    70, 1, 427, 6, 9,
    73, 1, 430, 6, 9,
    76, 1, 433, 6, 9,
    77, 0, 436, 6, 9,
    78, 0, 437, 6, 9,
    79, 0, 438, 6, 9,
    80, 0, 439, 6, 9,
    81, 0, 440, 6, 9,
    82, 1, 441, 6, 9,
    84, 0, 444, 6, 9,
    85, 1, 445, 6, 9,
    87, 1, 448, 6, 9,
    88, 1, 451, 6, 9,
    90, 1, 454, 6, 9,
    92, 1, 457, 6, 9,
    94, 1, 460, 6, 9,
    96, 1, 463, 6, 9,
    97, 1, 466, 6, 9,
    99, 1, 469, 6, 9,
    101, 1, 472, 6, 9,
    103, 1, 475, 6, 9,
    105, 1, 478, 6, 9,
    106, 2, 481, 6, 9,
    108, 1, 486, 6, 9,
    109, 1, 489, 6, 9,
    110, 2, 492, 6, 9,
    111, 1, 497, 6, 9,
    114, 1, 500, 6, 9,
    115, 1, 503, 6, 9,
    116, 1, 506, 6, 9,
    117, 1, 509, 6, 9,
    119, 1, 512, 6, 9,
    120, 1, 515, 6, 9,
    121, 1, 518, 6, 9,
    122, 2, 521, 6, 9,
    125, 3, 526, 6, 9,
    127, 0, 533, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, QMetaType::Bool, 13,
    QMetaType::Void, QMetaType::Bool, 19,
    QMetaType::Void, QMetaType::UInt, 22,
    QMetaType::Void, QMetaType::UInt, 24,
    QMetaType::Void, QMetaType::Bool, 27,
    QMetaType::Void, QMetaType::Bool, 29,
    QMetaType::Void, QMetaType::Bool, 31,
    QMetaType::Void, 0x80000000 | 33, 34,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, 0x80000000 | 39, 40,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 42, 43, 44, 45,
    QMetaType::Void, QMetaType::QString, 47,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 47, 49, 50,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 9, 10,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::QString,
    QMetaType::Double,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::QString, QMetaType::Int, 65,
    QMetaType::Int,
    QMetaType::Int,
    0x80000000 | 69,
    QMetaType::Bool, 0x80000000 | 71, 72,
    QMetaType::Bool, 0x80000000 | 74, 75,
    QMetaType::Bool, 0x80000000 | 9, 10,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 83,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 86,
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, QMetaType::Bool, 89,
    QMetaType::Void, QMetaType::QColor, 91,
    QMetaType::Void, QMetaType::QColor, 93,
    QMetaType::Void, QMetaType::Bool, 95,
    QMetaType::Void, QMetaType::Bool, 13,
    QMetaType::Void, QMetaType::QColor, 98,
    QMetaType::Void, QMetaType::QString, 100,
    QMetaType::Void, QMetaType::Double, 102,
    QMetaType::Void, QMetaType::QColor, 104,
    QMetaType::Void, QMetaType::Bool, 19,
    QMetaType::Void, 0x80000000 | 71, QMetaType::Bool, 72, 107,
    QMetaType::Void, QMetaType::UInt, 22,
    QMetaType::Void, QMetaType::UInt, 24,
    QMetaType::Void, 0x80000000 | 74, QMetaType::Bool, 75, 107,
    QMetaType::Void, 0x80000000 | 112, 113,
    QMetaType::Void, QMetaType::Bool, 27,
    QMetaType::Void, QMetaType::Bool, 29,
    QMetaType::Void, QMetaType::Bool, 31,
    QMetaType::Void, QMetaType::Bool, 118,
    QMetaType::Void, 0x80000000 | 33, 34,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, 0x80000000 | 39, 40,
    QMetaType::Void, QMetaType::QString, QMetaType::Bool, 123, 124,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Bool, 123, 126, 124,
    QMetaType::Void,

 // properties: name, type, flags
    86, QMetaType::Bool, 0x01015003, 		 // bool AsFormUI
    7, QMetaType::Bool, 0x01015003, 		 // bool AsNativeUI
    89, QMetaType::Bool, 0x01015003, 		 // bool DefaultAction
    91, QMetaType::QColor, 0x43015003, 		 // QColor DesignEdgeColor
    93, QMetaType::QColor, 0x43015003, 		 // QColor DesignGridColor
    95, QMetaType::Bool, 0x01015003, 		 // bool Dirty
    13, QMetaType::Bool, 0x01015003, 		 // bool EnableQuickEdit
    128, QMetaType::Bool, 0x01005001, 		 // bool IsBlank
    129, QMetaType::Bool, 0x01005001, 		 // bool IsInsertingControl
    19, QMetaType::Bool, 0x01015003, 		 // bool OnlyLayout
    22, QMetaType::UInt, 0x03015003, 		 // uint Options
    24, QMetaType::UInt, 0x03015003, 		 // uint Published
    113, 0x80000000 | 112, 0x00015003, 		 // IDispatch* Report
    27, QMetaType::Bool, 0x01015003, 		 // bool ShowExplorer
    29, QMetaType::Bool, 0x01015003, 		 // bool ShowInspector
    31, QMetaType::Bool, 0x01015003, 		 // bool ShowToolbar
    118, QMetaType::Bool, 0x01015003, 		 // bool ViewFloatSection
    34, 0x80000000 | 33, 0x0201500b, 		 // tagGRDesignerViewMode ViewMode
    37, 0x80000000 | 36, 0x0201500b, 		 // tagGRDesignerViewStyle ViewStyle
    40, 0x80000000 | 39, 0x0201500b, 		 // tagGRDesignerWindowLayout WindowLayout
    261, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    9, 0x0, 72, 625, 
    71, 0x0, 15, 769, 
    33, 0x0, 5, 799, 
    36, 0x0, 9, 809, 
    39, 0x0, 2, 827, 
    74, 0x0, 7, 831, 
    69, 0x0, 20, 845, 

 // enum data: key, value
    130, uint(grdesLib::grdaEditUndo),
    131, uint(grdesLib::grdaEditRedo),
    132, uint(grdesLib::grdaEditCut),
    133, uint(grdesLib::grdaEditPaste),
    134, uint(grdesLib::grdaEditCopy),
    135, uint(grdesLib::grdaEditDelete),
    136, uint(grdesLib::grdaEditSelectAll),
    137, uint(grdesLib::grdaAutoSizeControl),
    138, uint(grdesLib::grdaAutoGenColumn),
    139, uint(grdesLib::grdaAutoGenField),
    140, uint(grdesLib::grdaSectionMoveUp),
    141, uint(grdesLib::grdaSectionMoveDown),
    142, uint(grdesLib::grdaAutoGenParameter),
    143, uint(grdesLib::grdaReportPaperSetting),
    144, uint(grdesLib::grdaSetupDBQuery),
    145, uint(grdesLib::grdaReportParameterCollection),
    146, uint(grdesLib::grdaReportGroupCollection),
    147, uint(grdesLib::grdaReportColumnCollection),
    148, uint(grdesLib::grdaReportFieldCollection),
    149, uint(grdesLib::grdaReportColumnTitleLayout),
    150, uint(grdesLib::grdaBrowseScriptCode),
    151, uint(grdesLib::grdaExitSubReportDesign),
    152, uint(grdesLib::grdaSetupParamDBQuery),
    153, uint(grdesLib::grdaInsertReportHeader),
    154, uint(grdesLib::grdaInsertReportFooter),
    155, uint(grdesLib::grdaInsertPageHeader),
    156, uint(grdesLib::grdaInsertPageFooter),
    157, uint(grdesLib::grdaInsertDetailGrid),
    158, uint(grdesLib::grdaInsertGroup),
    159, uint(grdesLib::grdaInsertField),
    160, uint(grdesLib::grdaInsertColumn),
    161, uint(grdesLib::grdaInsertParameter),
    162, uint(grdesLib::grdaFormatAlignLeft),
    163, uint(grdesLib::grdaFormatAlignRight),
    164, uint(grdesLib::grdaFormatAlignCenter),
    165, uint(grdesLib::grdaFormatAlignTop),
    166, uint(grdesLib::grdaFormatAlignMiddle),
    167, uint(grdesLib::grdaFormatAlignBottom),
    168, uint(grdesLib::grdaFormatAlignToGrid),
    169, uint(grdesLib::grdaFormatSizeSameWidth),
    170, uint(grdesLib::grdaFormatSizeSameHeight),
    171, uint(grdesLib::grdaFormatSizeSameBoth),
    172, uint(grdesLib::grdaFormatSizeToGrid),
    173, uint(grdesLib::grdaFormatSpaceEquallyVertical),
    174, uint(grdesLib::grdaFormatSpaceIncreaseVertical),
    175, uint(grdesLib::grdaFormatSpaceDecreaseVertical),
    176, uint(grdesLib::grdaFormatSpaceEquallyHorizontal),
    177, uint(grdesLib::grdaFormatSpaceIncreaseHorizontal),
    178, uint(grdesLib::grdaFormatSpaceDecreaseHorizontal),
    179, uint(grdesLib::grdaFormatSpaceRemoveHorizontal),
    180, uint(grdesLib::grdaFormatSpaceRemoveVertical),
    181, uint(grdesLib::grdaFormatOrderBringToFront),
    182, uint(grdesLib::grdaFormatOrderSendToBack),
    183, uint(grdesLib::grdaFormatFontStrikethrough),
    184, uint(grdesLib::grdaFormatFontBold),
    185, uint(grdesLib::grdaFormatFontItalic),
    186, uint(grdesLib::grdaFormatFontUnderline),
    187, uint(grdesLib::grdaFormatTextAlignTopLeft),
    188, uint(grdesLib::grdaFormatTextAlignTopCenter),
    189, uint(grdesLib::grdaFormatTextAlignTopRight),
    190, uint(grdesLib::grdaFormatTextAlignMiddleLeft),
    191, uint(grdesLib::grdaFormatTextAlignMiddleCenter),
    192, uint(grdesLib::grdaFormatTextAlignMiddleRight),
    193, uint(grdesLib::grdaFormatTextAlignBottomLeft),
    194, uint(grdesLib::grdaFormatTextAlignBottomCenter),
    195, uint(grdesLib::grdaFormatTextAlignBottomRight),
    196, uint(grdesLib::grdaFormatTextOrientationDefault),
    197, uint(grdesLib::grdaFormatTextOrientationU2DL2R0),
    198, uint(grdesLib::grdaFormatTextOrientationD2UL2R1),
    199, uint(grdesLib::grdaFormatTextOrientationU2DR2L0),
    200, uint(grdesLib::grdaFormatTextOrientationU2DR2L1),
    201, uint(grdesLib::grdaFormatTextOrientationInvert),
    202, uint(grdesLib::grdoShowRuler),
    203, uint(grdesLib::grdoCanPopupMenu),
    204, uint(grdesLib::grdoShowInspector),
    205, uint(grdesLib::grdoShowInspectorObjectPicker),
    206, uint(grdesLib::grdoShowExplorer),
    207, uint(grdesLib::grdoShowToolbar),
    208, uint(grdesLib::grdoShowSectionLine),
    209, uint(grdesLib::grdoShowMarginLine),
    210, uint(grdesLib::grdoCanResizeSection),
    211, uint(grdesLib::grdoCanChangeMargin),
    212, uint(grdesLib::grdoCanDeleteObject),
    213, uint(grdesLib::grdoEnableQuickEdit),
    214, uint(grdesLib::grdoShowDetailGridToolbar),
    215, uint(grdesLib::grdoShowDetailGridColumnRuler),
    216, uint(grdesLib::grdoCanModifyDBSettings),
    217, uint(grdesLib::grvmInNormalDesign),
    218, uint(grdesLib::grvmInPageDesign),
    219, uint(grdesLib::grvmInPrint),
    220, uint(grdesLib::grvmInDisplay),
    221, uint(grdesLib::grvmInScript),
    222, uint(grdesLib::grvsOnlyNormal),
    223, uint(grdesLib::grvsOnlyPage),
    224, uint(grdesLib::grvsNormalPage),
    225, uint(grdesLib::grvsNomalPrint),
    226, uint(grdesLib::grvsNomalPrintDisplay),
    227, uint(grdesLib::grvsPagePrint),
    228, uint(grdesLib::grvsPagePrintDisplay),
    229, uint(grdesLib::grvsNomalPagePrint),
    230, uint(grdesLib::grvsNomalPagePrintDisplay),
    231, uint(grdesLib::grdwlLayoutAtLeft),
    232, uint(grdesLib::grdwlLayoutAtRight),
    233, uint(grdesLib::grpcDesign),
    234, uint(grdesLib::grpcLayout),
    235, uint(grdesLib::grpcAppearance),
    236, uint(grdesLib::grpcData),
    237, uint(grdesLib::grpcAction),
    238, uint(grdesLib::grpcEvent),
    239, uint(grdesLib::grpcMisc),
    240, uint(grdesLib::grdssReport),
    241, uint(grdesLib::grdssPageHeader),
    242, uint(grdesLib::grdssPageFooter),
    243, uint(grdesLib::grdssReportHeader),
    244, uint(grdesLib::grdssReportFooter),
    245, uint(grdesLib::grdssControlSingle),
    246, uint(grdesLib::grdssControlMulti),
    247, uint(grdesLib::grdssDetailGrid),
    248, uint(grdesLib::grdssColumn),
    249, uint(grdesLib::grdssColumnContentCell),
    250, uint(grdesLib::grdssColumnTitleCell),
    251, uint(grdesLib::grdssColumnContent),
    252, uint(grdesLib::grdssColumnTitle),
    253, uint(grdesLib::grdssGroup),
    254, uint(grdesLib::grdssGroupHeader),
    255, uint(grdesLib::grdssGroupFooter),
    256, uint(grdesLib::grdssRecordset),
    257, uint(grdesLib::grdssField),
    258, uint(grdesLib::grdssParameter),
    259, uint(grdesLib::grdssCrossTab),
    0 // eod
};

const QMetaObject IGRDesigner::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_grdesLib__IGRDesigner, 0, 0, 0 }
};

void *IGRDesigner::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "grdesLib::IGRDesigner"))
        return static_cast<void*>(const_cast<IGRDesigner*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_grdesLib__DesignerProps[] = {

 // content:
    7, // revision
    262,  // classname
    0, 0, // classinfo
    3, 14, // methods
    0, 0, // properties
    7, 48, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    41, 4, 29, 6, 5,
    46, 1, 38, 6, 5,
    48, 3, 41, 6, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 42, 43, 44, 45,
    QMetaType::Void, QMetaType::QString, 47,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 47, 49, 50,

 // enums: name, flags, count, data
    9, 0x0, 72, 76, 
    71, 0x0, 15, 220, 
    33, 0x0, 5, 250, 
    36, 0x0, 9, 260, 
    39, 0x0, 2, 278, 
    74, 0x0, 7, 282, 
    69, 0x0, 20, 296, 

 // enum data: key, value
    130, uint(grdesLib::grdaEditUndo),
    131, uint(grdesLib::grdaEditRedo),
    132, uint(grdesLib::grdaEditCut),
    133, uint(grdesLib::grdaEditPaste),
    134, uint(grdesLib::grdaEditCopy),
    135, uint(grdesLib::grdaEditDelete),
    136, uint(grdesLib::grdaEditSelectAll),
    137, uint(grdesLib::grdaAutoSizeControl),
    138, uint(grdesLib::grdaAutoGenColumn),
    139, uint(grdesLib::grdaAutoGenField),
    140, uint(grdesLib::grdaSectionMoveUp),
    141, uint(grdesLib::grdaSectionMoveDown),
    142, uint(grdesLib::grdaAutoGenParameter),
    143, uint(grdesLib::grdaReportPaperSetting),
    144, uint(grdesLib::grdaSetupDBQuery),
    145, uint(grdesLib::grdaReportParameterCollection),
    146, uint(grdesLib::grdaReportGroupCollection),
    147, uint(grdesLib::grdaReportColumnCollection),
    148, uint(grdesLib::grdaReportFieldCollection),
    149, uint(grdesLib::grdaReportColumnTitleLayout),
    150, uint(grdesLib::grdaBrowseScriptCode),
    151, uint(grdesLib::grdaExitSubReportDesign),
    152, uint(grdesLib::grdaSetupParamDBQuery),
    153, uint(grdesLib::grdaInsertReportHeader),
    154, uint(grdesLib::grdaInsertReportFooter),
    155, uint(grdesLib::grdaInsertPageHeader),
    156, uint(grdesLib::grdaInsertPageFooter),
    157, uint(grdesLib::grdaInsertDetailGrid),
    158, uint(grdesLib::grdaInsertGroup),
    159, uint(grdesLib::grdaInsertField),
    160, uint(grdesLib::grdaInsertColumn),
    161, uint(grdesLib::grdaInsertParameter),
    162, uint(grdesLib::grdaFormatAlignLeft),
    163, uint(grdesLib::grdaFormatAlignRight),
    164, uint(grdesLib::grdaFormatAlignCenter),
    165, uint(grdesLib::grdaFormatAlignTop),
    166, uint(grdesLib::grdaFormatAlignMiddle),
    167, uint(grdesLib::grdaFormatAlignBottom),
    168, uint(grdesLib::grdaFormatAlignToGrid),
    169, uint(grdesLib::grdaFormatSizeSameWidth),
    170, uint(grdesLib::grdaFormatSizeSameHeight),
    171, uint(grdesLib::grdaFormatSizeSameBoth),
    172, uint(grdesLib::grdaFormatSizeToGrid),
    173, uint(grdesLib::grdaFormatSpaceEquallyVertical),
    174, uint(grdesLib::grdaFormatSpaceIncreaseVertical),
    175, uint(grdesLib::grdaFormatSpaceDecreaseVertical),
    176, uint(grdesLib::grdaFormatSpaceEquallyHorizontal),
    177, uint(grdesLib::grdaFormatSpaceIncreaseHorizontal),
    178, uint(grdesLib::grdaFormatSpaceDecreaseHorizontal),
    179, uint(grdesLib::grdaFormatSpaceRemoveHorizontal),
    180, uint(grdesLib::grdaFormatSpaceRemoveVertical),
    181, uint(grdesLib::grdaFormatOrderBringToFront),
    182, uint(grdesLib::grdaFormatOrderSendToBack),
    183, uint(grdesLib::grdaFormatFontStrikethrough),
    184, uint(grdesLib::grdaFormatFontBold),
    185, uint(grdesLib::grdaFormatFontItalic),
    186, uint(grdesLib::grdaFormatFontUnderline),
    187, uint(grdesLib::grdaFormatTextAlignTopLeft),
    188, uint(grdesLib::grdaFormatTextAlignTopCenter),
    189, uint(grdesLib::grdaFormatTextAlignTopRight),
    190, uint(grdesLib::grdaFormatTextAlignMiddleLeft),
    191, uint(grdesLib::grdaFormatTextAlignMiddleCenter),
    192, uint(grdesLib::grdaFormatTextAlignMiddleRight),
    193, uint(grdesLib::grdaFormatTextAlignBottomLeft),
    194, uint(grdesLib::grdaFormatTextAlignBottomCenter),
    195, uint(grdesLib::grdaFormatTextAlignBottomRight),
    196, uint(grdesLib::grdaFormatTextOrientationDefault),
    197, uint(grdesLib::grdaFormatTextOrientationU2DL2R0),
    198, uint(grdesLib::grdaFormatTextOrientationD2UL2R1),
    199, uint(grdesLib::grdaFormatTextOrientationU2DR2L0),
    200, uint(grdesLib::grdaFormatTextOrientationU2DR2L1),
    201, uint(grdesLib::grdaFormatTextOrientationInvert),
    202, uint(grdesLib::grdoShowRuler),
    203, uint(grdesLib::grdoCanPopupMenu),
    204, uint(grdesLib::grdoShowInspector),
    205, uint(grdesLib::grdoShowInspectorObjectPicker),
    206, uint(grdesLib::grdoShowExplorer),
    207, uint(grdesLib::grdoShowToolbar),
    208, uint(grdesLib::grdoShowSectionLine),
    209, uint(grdesLib::grdoShowMarginLine),
    210, uint(grdesLib::grdoCanResizeSection),
    211, uint(grdesLib::grdoCanChangeMargin),
    212, uint(grdesLib::grdoCanDeleteObject),
    213, uint(grdesLib::grdoEnableQuickEdit),
    214, uint(grdesLib::grdoShowDetailGridToolbar),
    215, uint(grdesLib::grdoShowDetailGridColumnRuler),
    216, uint(grdesLib::grdoCanModifyDBSettings),
    217, uint(grdesLib::grvmInNormalDesign),
    218, uint(grdesLib::grvmInPageDesign),
    219, uint(grdesLib::grvmInPrint),
    220, uint(grdesLib::grvmInDisplay),
    221, uint(grdesLib::grvmInScript),
    222, uint(grdesLib::grvsOnlyNormal),
    223, uint(grdesLib::grvsOnlyPage),
    224, uint(grdesLib::grvsNormalPage),
    225, uint(grdesLib::grvsNomalPrint),
    226, uint(grdesLib::grvsNomalPrintDisplay),
    227, uint(grdesLib::grvsPagePrint),
    228, uint(grdesLib::grvsPagePrintDisplay),
    229, uint(grdesLib::grvsNomalPagePrint),
    230, uint(grdesLib::grvsNomalPagePrintDisplay),
    231, uint(grdesLib::grdwlLayoutAtLeft),
    232, uint(grdesLib::grdwlLayoutAtRight),
    233, uint(grdesLib::grpcDesign),
    234, uint(grdesLib::grpcLayout),
    235, uint(grdesLib::grpcAppearance),
    236, uint(grdesLib::grpcData),
    237, uint(grdesLib::grpcAction),
    238, uint(grdesLib::grpcEvent),
    239, uint(grdesLib::grpcMisc),
    240, uint(grdesLib::grdssReport),
    241, uint(grdesLib::grdssPageHeader),
    242, uint(grdesLib::grdssPageFooter),
    243, uint(grdesLib::grdssReportHeader),
    244, uint(grdesLib::grdssReportFooter),
    245, uint(grdesLib::grdssControlSingle),
    246, uint(grdesLib::grdssControlMulti),
    247, uint(grdesLib::grdssDetailGrid),
    248, uint(grdesLib::grdssColumn),
    249, uint(grdesLib::grdssColumnContentCell),
    250, uint(grdesLib::grdssColumnTitleCell),
    251, uint(grdesLib::grdssColumnContent),
    252, uint(grdesLib::grdssColumnTitle),
    253, uint(grdesLib::grdssGroup),
    254, uint(grdesLib::grdssGroupHeader),
    255, uint(grdesLib::grdssGroupFooter),
    256, uint(grdesLib::grdssRecordset),
    257, uint(grdesLib::grdssField),
    258, uint(grdesLib::grdssParameter),
    259, uint(grdesLib::grdssCrossTab),
    0 // eod
};

const QMetaObject DesignerProps::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_grdesLib__DesignerProps, 0, 0, 0 }
};

void *DesignerProps::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "grdesLib::DesignerProps"))
        return static_cast<void*>(const_cast<DesignerProps*>(this));
    return QAxObject::qt_metacast(_clname);
}

